apiVersion: v1
kind: ServiceAccount
metadata:
  name: whatsmyip
---
apiVersion: v1
kind: Service
metadata:
  name: whatsmyip
  labels:
    app: whatsmyip
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: whatsmyip
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whatsmyip-v1
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whatsmyip
        version: v1
    spec:
      serviceAccountName: whatsmyip
      containers:
      - name: whatsmyip
        image: whatsmyip:latest
        command: ["/usr/bin/whatsmyip", "3650d"]
        imagePullPolicy: Never
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: whatsmyip
spec:
  hosts:
  - whatsmyip
  http:
  - route:
    - destination:
        host: whatsmyip
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: whatsmyip
spec:
  host: whatsmyip
  subsets:
  - name: v1
    labels:
      version: v1
---